---
settings:
  name: BlueXP cloud ops
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: BlueXP Cloud操作文档
    url: "/index.html"
  - title: 发行说明
    url: "/whats-new.html"
  - title: 入门
    entries:
    - title: 了解BlueXP云操作
      url: "/concept-compute.html"
    - title: 连接您的 AWS 帐户
      url: "/task-getting-started-compute.html"
  - title: 分析计算成本
    url: "/task-analyze-costs.html"
  - title: 知识和支持
    entries:
    - title: 注册以获得支持
      url: "/task-support-registration.html"
    - title: 获取帮助
      url: "/task-get-help.html"
  - title: 法律声明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 入门
    links:
    - title: 了解BlueXP云操作
      url: concept-compute.html
    - title: 连接您的 AWS 帐户
      url: task-getting-started-compute.html
  - title: 使用BlueXP云操作
    links:
    - title: 分析计算成本
      url: task-analyze-costs.html
  - title: 博客社区
    links:
    - title: NetApp 社区
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: BlueXP博客
      url: https://cloud.netapp.com/blog
    - title: 云网络研讨会
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: 所有BlueXP文档
